name: Publish Policies to Cerbos Hub

on:
  push:
    branches:
      - main
    paths:
      - "policies/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install cerbosctl
        run: |
          wget -q https://github.com/cerbos/cerbos/releases/download/v0.53.0/cerbosctl_0.53.0_Linux_x86_64.tar.gz
          tar -xzf cerbosctl_0.53.0_Linux_x86_64.tar.gz
          chmod +x cerbosctl
      
      - name: Publish to Cerbos Hub
        run: |
          ./cerbosctl hub store add-files --store-id="${{ secrets.CERBOS_HUB_STORE_ID }}" --client-id="${{ secrets.CERBOS_HUB_CLIENT_ID }}" --client-secret="${{ secrets.CERBOS_HUB_CLIENT_SECRET }}" policies/*.yaml

