name: Publish Policies to Cerbos Hub

on:
  push:
    branches:
      - main
    paths:
      - 'policies/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Publish to Cerbos Hub
        uses: cerbos/cerbos-store-action@v1
        with:
          store-id: ${{ secrets.CERBOS_HUB_STORE_ID }}
          client-id: ${{ secrets.CERBOS_HUB_CLIENT_ID }}
          client-secret: ${{ secrets.CERBOS_HUB_CLIENT_SECRET }}
          directory: policies/
